"""Evidence storage abstraction.

Image bytes are kept out of the database and behind a small interface so that
an S3-backed implementation can be added later (see
``docs/architecture/aws.md``). Only the local implementation exists today.
"""

from __future__ import annotations

import hashlib
from abc import ABC, abstractmethod
from pathlib import Path


class EvidenceStorage(ABC):
    """Stores and retrieves image evidence by opaque key."""

    @abstractmethod
    def put(self, inspection_id: str, image_id: str, suffix: str, data: bytes) -> str:
        """Store ``data`` and return the storage key."""

    @abstractmethod
    def get(self, key: str) -> bytes: ...

    @abstractmethod
    def exists(self, key: str) -> bool: ...


class LocalEvidenceStorage(EvidenceStorage):
    """Filesystem implementation rooted at a single directory.

    Keys are always ``<inspection_id>/<filename>`` where the inspection id is
    generated by the application and the filename is derived from an image id,
    so a key can never traverse out of the root.
    """

    def __init__(self, root: Path) -> None:
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        candidate = (self.root / key).resolve()
        root = self.root.resolve()
        if not str(candidate).startswith(str(root)):
            raise ValueError("evidence key escapes storage root")
        return candidate

    def put(self, inspection_id: str, image_id: str, suffix: str, data: bytes) -> str:
        suffix = suffix if suffix.startswith(".") else f".{suffix}"
        key = f"{inspection_id}/{image_id}{suffix}"
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return key

    def get(self, key: str) -> bytes:
        return self._resolve(key).read_bytes()

    def exists(self, key: str) -> bool:
        return self._resolve(key).is_file()


def sha256_of(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()
